server:
  port: 8080
database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  name: "test"

redis:
  host: "localhost"
  port: 6379
  password: "123456"
  db: 0

log:
  level: "info"

api:
  user: "http://user.api.com"
  order: "http://order.api.com"